apiVersion: batch/v1
kind: Job
metadata:
  labels:
    run: rabbitmq-publisher
  name: rabbitmq-publisher
spec:
  template:
    metadata:
      labels:
        run: rabbitmq-publisher
    spec:
      containers:
      - image: felipecruz/rabbitmq-publisher:dev
        imagePullPolicy: IfNotPresent
        name: rabbitmq-publisher
        env:
          - name: RABBITMQ_USER
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: user
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: password                     
        envFrom:
        - configMapRef:
            name: publisher-config 
        resources: {}
      restartPolicy: OnFailure
  backoffLimit: 4      
status: {}
