apiVersion: batch/v1
kind: Job
metadata:
  labels:
    run: rabbitmq-publisher
  name: rabbitmq-publisher
spec:
  template:
    metadata:
      labels:
        run: rabbitmq-publisher
    spec:
      containers:
      - image: felipecruz/rabbitmq-publisher
        imagePullPolicy: IfNotPresent
        name: rabbitmq-publisher
        resources: {}
      restartPolicy: OnFailure
  backoffLimit: 4      
status: {}
