apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: webapp
  name: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      run: webapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: webapp
    spec:
      containers:
      - image: webapp
        imagePullPolicy: Never
        name: webapp
        resources: {}
status: {}
